const character={name:"沈七月",age:22,height:"168 cm",look:"youthful doll-like face, natural long straight black hair, slim long-limbed body",outfit:"loose pale gray/off-white short-sleeve T-shirt, dark gray straight casual pants, white casual shoes, simple black crossbody bag",style:"high-quality Chinese 3D donghua character model, PBR materials, cinematic lighting, stylized animation proportions, not live-action photorealism"};
const CONFIG={apiBase:localStorage.getItem("fulingApiBase")||"",provider:"hf-ltx",model:"Lightricks/LTX-Video"};
let current=Number(localStorage.getItem("fulingShot")||1),shots=JSON.parse(localStorage.getItem("fulingShots")||"[]");if(!shots.length)shots=[{id:1,status:"等待生成"}];
const $=s=>document.querySelector(s),shot=$("#shot"),prompt=$("#prompt"),refInput=$("#refInput"),refImg=$("#refImg"),refEmpty=$("#refEmpty");
function id(n){return "S01-"+String(n).padStart(3,"0")}function save(){localStorage.setItem("fulingShot",current);localStorage.setItem("fulingShots",JSON.stringify(shots))}
function render(){const s=shots.find(x=>x.id===current)||{};$("#shotId").textContent=id(current)+" · "+(s.status||"尚未生成");$("#history").innerHTML=shots.map(s=>'<div class="history"><b>'+id(s.id)+'</b><span>'+s.status+'</span></div>').join("");save()}
function buildPrompt(){return `Cinematic high-quality Chinese 3D donghua animation. Character: ${character.name}, ${character.age} years old, ${character.height}, ${character.look}. Outfit locked: ${character.outfit}. Visual style: ${character.style}. Scene: ${$("#scene").value}. Shot: ${shot.value} Keep the same face, hairstyle, age, body proportions, clothes and black crossbody bag as the reference image. Natural motion, physically plausible cloth and hair movement, cinematic camera, shallow depth of field. No fantasy costume, no armor, no unintended transformation, no appearance drift. Pre-awakening Shen Qiyue remains youthful and gentle unless this shot explicitly says otherwise.`}
$("#promptBtn").onclick=()=>prompt.value=buildPrompt();
$("#chooseRef").onclick=()=>refInput.click();$("#refBox").onclick=()=>refInput.click();
refInput.onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>4*1024*1024){alert("母圖請控制在 4MB 以內。");return}const r=new FileReader;r.onload=()=>{try{localStorage.setItem("shenQiyueRef",r.result)}catch(err){alert("圖片太大，Safari 無法保存。請換較小的母圖。");return}showRef(r.result)};r.readAsDataURL(f)};
function showRef(src){refImg.src=src;refImg.style.display="block";refEmpty.style.display="none"}const savedRef=localStorage.getItem("shenQiyueRef");if(savedRef)showRef(savedRef);
$("#removeRef").onclick=()=>{localStorage.removeItem("shenQiyueRef");refImg.removeAttribute("src");refImg.style.display="none";refEmpty.style.display="block";refInput.value=""};
function setStatus(t){$("#status").textContent=t}function updateShot(status,videoUrl){let s=shots.find(x=>x.id===current);if(!s){s={id:current};shots.push(s)}s.status=status;if(videoUrl)s.videoUrl=videoUrl;render()}
async function generate(){if(!savedRef&&!localStorage.getItem("shenQiyueRef")){setStatus("請先加入沈七月母圖。");return}if(!prompt.value.trim())prompt.value=buildPrompt();if(!CONFIG.apiBase){setStatus("v1.2 Provider Adapter 已完成。下一步只差安全後端：目前不會上傳母圖，也不會消耗任何額度。");return}try{updateShot("生成中…");setStatus("正在建立影片工作…");const res=await fetch(CONFIG.apiBase+"/api/video",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider:$("#provider").value,model:CONFIG.model,prompt:prompt.value,image:localStorage.getItem("shenQiyueRef"),duration:Number($("#duration").value),aspectRatio:"16:9"})});if(!res.ok)throw new Error("HTTP "+res.status);const data=await res.json();if(data.videoUrl){showVideo(data.videoUrl);updateShot("✓ 已完成",data.videoUrl);setStatus("影片完成。")}else if(data.taskId){updateShot("生成中…");setStatus("影片工作已送出："+data.taskId)}else throw new Error("後端沒有回傳 videoUrl/taskId")}catch(e){updateShot("生成失敗");setStatus("生成失敗："+e.message)}}
function showVideo(url){const v=$("#videoPreview");v.src=url;$(".preview").classList.add("hasVideo");v.load()}
$("#generate").onclick=generate;
$("#nextShot").onclick=()=>{current=Math.max(...shots.map(s=>s.id))+1;shots.push({id:current,status:"等待生成"});shot.value="";prompt.value="";render();window.scrollTo({top:0,behavior:"smooth"})};
$("#provider").onchange=()=>{const p=$("#provider").value;$("#engineTitle").textContent=p==="hf-ltx"?"LTX Adapter Ready":"Provider Adapter";};
render();const cur=shots.find(x=>x.id===current);if(cur&&cur.videoUrl)showVideo(cur.videoUrl);
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js?v=12").then(r=>r.update());